# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CRLcalc_qt.ui'
#
# Created: Mon Apr 18 21:46:00 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ScrollArea(object):
    def setupUi(self, ScrollArea):
        ScrollArea.setObjectName(_fromUtf8("ScrollArea"))
        ScrollArea.resize(973, 598)
        ScrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 971, 596))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.layoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 971, 601))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.Field_Energy = QtGui.QLineEdit(self.groupBox)
        self.Field_Energy.setGeometry(QtCore.QRect(60, 30, 113, 27))
        self.Field_Energy.setObjectName(_fromUtf8("Field_Energy"))
        self.Name_Energy = QtGui.QLabel(self.groupBox)
        self.Name_Energy.setGeometry(QtCore.QRect(0, 30, 56, 17))
        self.Name_Energy.setObjectName(_fromUtf8("Name_Energy"))
        self.Unit_Energy = QtGui.QLabel(self.groupBox)
        self.Unit_Energy.setGeometry(QtCore.QRect(180, 30, 56, 17))
        self.Unit_Energy.setObjectName(_fromUtf8("Unit_Energy"))
        self.Field_WaveLength = QtGui.QLineEdit(self.groupBox)
        self.Field_WaveLength.setGeometry(QtCore.QRect(60, 60, 113, 27))
        self.Field_WaveLength.setObjectName(_fromUtf8("Field_WaveLength"))
        self.unit_WaveLength = QtGui.QLabel(self.groupBox)
        self.unit_WaveLength.setGeometry(QtCore.QRect(180, 60, 56, 17))
        self.unit_WaveLength.setObjectName(_fromUtf8("unit_WaveLength"))
        self.Name_WaveLength = QtGui.QLabel(self.groupBox)
        self.Name_WaveLength.setGeometry(QtCore.QRect(0, 60, 56, 17))
        self.Name_WaveLength.setObjectName(_fromUtf8("Name_WaveLength"))
        self.line_4 = QtGui.QFrame(self.groupBox)
        self.line_4.setGeometry(QtCore.QRect(10, 90, 221, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_46 = QtGui.QLabel(self.groupBox)
        self.label_46.setGeometry(QtCore.QRect(10, 110, 56, 17))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.Field_SSv = QtGui.QLineEdit(self.groupBox)
        self.Field_SSv.setGeometry(QtCore.QRect(70, 130, 113, 27))
        self.Field_SSv.setObjectName(_fromUtf8("Field_SSv"))
        self.Unit_SSv = QtGui.QLabel(self.groupBox)
        self.Unit_SSv.setGeometry(QtCore.QRect(190, 130, 56, 17))
        self.Unit_SSv.setObjectName(_fromUtf8("Unit_SSv"))
        self.Name_SSv = QtGui.QLabel(self.groupBox)
        self.Name_SSv.setGeometry(QtCore.QRect(10, 130, 56, 17))
        self.Name_SSv.setObjectName(_fromUtf8("Name_SSv"))
        self.Field_SSh = QtGui.QLineEdit(self.groupBox)
        self.Field_SSh.setGeometry(QtCore.QRect(70, 160, 113, 27))
        self.Field_SSh.setObjectName(_fromUtf8("Field_SSh"))
        self.Unit_SSh = QtGui.QLabel(self.groupBox)
        self.Unit_SSh.setGeometry(QtCore.QRect(190, 160, 56, 17))
        self.Unit_SSh.setObjectName(_fromUtf8("Unit_SSh"))
        self.Name_SSh = QtGui.QLabel(self.groupBox)
        self.Name_SSh.setGeometry(QtCore.QRect(10, 160, 56, 17))
        self.Name_SSh.setObjectName(_fromUtf8("Name_SSh"))
        self.line_5 = QtGui.QFrame(self.groupBox)
        self.line_5.setGeometry(QtCore.QRect(10, 190, 231, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.Field_g = QtGui.QLineEdit(self.groupBox)
        self.Field_g.setGeometry(QtCore.QRect(70, 200, 113, 27))
        self.Field_g.setObjectName(_fromUtf8("Field_g"))
        self.Unit_g = QtGui.QLabel(self.groupBox)
        self.Unit_g.setGeometry(QtCore.QRect(190, 200, 56, 17))
        self.Unit_g.setObjectName(_fromUtf8("Unit_g"))
        self.Name_g = QtGui.QLabel(self.groupBox)
        self.Name_g.setGeometry(QtCore.QRect(10, 200, 56, 17))
        self.Name_g.setObjectName(_fromUtf8("Name_g"))
        self.Field_Intensity = QtGui.QLineEdit(self.groupBox)
        self.Field_Intensity.setGeometry(QtCore.QRect(70, 230, 113, 27))
        self.Field_Intensity.setObjectName(_fromUtf8("Field_Intensity"))
        self.Unit_Intensity = QtGui.QLabel(self.groupBox)
        self.Unit_Intensity.setGeometry(QtCore.QRect(190, 230, 56, 17))
        self.Unit_Intensity.setObjectName(_fromUtf8("Unit_Intensity"))
        self.Name_Intensity = QtGui.QLabel(self.groupBox)
        self.Name_Intensity.setGeometry(QtCore.QRect(10, 230, 56, 17))
        self.Name_Intensity.setObjectName(_fromUtf8("Name_Intensity"))
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEdit_17 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_17.setGeometry(QtCore.QRect(70, 30, 113, 27))
        self.lineEdit_17.setObjectName(_fromUtf8("lineEdit_17"))
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(190, 30, 56, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(10, 30, 56, 17))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.lineEdit_18 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_18.setGeometry(QtCore.QRect(70, 60, 113, 27))
        self.lineEdit_18.setObjectName(_fromUtf8("lineEdit_18"))
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(190, 60, 56, 17))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(10, 60, 56, 17))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox.setGeometry(QtCore.QRect(80, 90, 88, 22))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        self.line_3.setGeometry(QtCore.QRect(10, 110, 231, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.lineEdit_19 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_19.setGeometry(QtCore.QRect(70, 130, 113, 27))
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(190, 130, 56, 17))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(10, 130, 56, 17))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.lineEdit_20 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_20.setGeometry(QtCore.QRect(70, 160, 113, 27))
        self.lineEdit_20.setObjectName(_fromUtf8("lineEdit_20"))
        self.label_40 = QtGui.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(190, 160, 56, 17))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(10, 160, 56, 17))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.lineEdit_21 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_21.setGeometry(QtCore.QRect(70, 190, 113, 27))
        self.lineEdit_21.setObjectName(_fromUtf8("lineEdit_21"))
        self.label_42 = QtGui.QLabel(self.groupBox_2)
        self.label_42.setGeometry(QtCore.QRect(190, 190, 56, 17))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.groupBox_2)
        self.label_43.setGeometry(QtCore.QRect(10, 190, 56, 17))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.lineEdit_22 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_22.setGeometry(QtCore.QRect(70, 220, 113, 27))
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.label_44 = QtGui.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(190, 220, 56, 17))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.label_45 = QtGui.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(10, 220, 56, 17))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_55 = QtGui.QLabel(self.groupBox_3)
        self.label_55.setGeometry(QtCore.QRect(20, 30, 56, 17))
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(100, 20, 75, 33))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.lineEdit_27 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_27.setGeometry(QtCore.QRect(80, 70, 113, 27))
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.label_56 = QtGui.QLabel(self.groupBox_3)
        self.label_56.setGeometry(QtCore.QRect(200, 70, 56, 17))
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.label_57 = QtGui.QLabel(self.groupBox_3)
        self.label_57.setGeometry(QtCore.QRect(20, 70, 56, 17))
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.lineEdit_28 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_28.setGeometry(QtCore.QRect(80, 100, 113, 27))
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.label_58 = QtGui.QLabel(self.groupBox_3)
        self.label_58.setGeometry(QtCore.QRect(200, 100, 56, 17))
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_59 = QtGui.QLabel(self.groupBox_3)
        self.label_59.setGeometry(QtCore.QRect(20, 100, 56, 17))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.lineEdit_29 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_29.setGeometry(QtCore.QRect(80, 130, 113, 27))
        self.lineEdit_29.setObjectName(_fromUtf8("lineEdit_29"))
        self.label_60 = QtGui.QLabel(self.groupBox_3)
        self.label_60.setGeometry(QtCore.QRect(200, 130, 56, 17))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_61 = QtGui.QLabel(self.groupBox_3)
        self.label_61.setGeometry(QtCore.QRect(20, 130, 56, 17))
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 85, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(70, 40, 113, 27))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(190, 40, 56, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 56, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 70, 113, 27))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(190, 70, 56, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(10, 70, 56, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 100, 113, 27))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(190, 100, 56, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 56, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(70, 130, 113, 27))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(190, 130, 56, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(10, 130, 56, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(70, 160, 113, 27))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(190, 160, 56, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 160, 56, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(70, 190, 113, 27))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(190, 190, 56, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 190, 56, 17))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_62 = QtGui.QLabel(self.groupBox_6)
        self.label_62.setGeometry(QtCore.QRect(190, 30, 56, 17))
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.lineEdit_30 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_30.setGeometry(QtCore.QRect(70, 30, 113, 27))
        self.lineEdit_30.setObjectName(_fromUtf8("lineEdit_30"))
        self.label_63 = QtGui.QLabel(self.groupBox_6)
        self.label_63.setGeometry(QtCore.QRect(10, 30, 56, 17))
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.label_64 = QtGui.QLabel(self.groupBox_6)
        self.label_64.setGeometry(QtCore.QRect(190, 60, 56, 17))
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.lineEdit_31 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_31.setGeometry(QtCore.QRect(70, 60, 113, 27))
        self.lineEdit_31.setObjectName(_fromUtf8("lineEdit_31"))
        self.label_65 = QtGui.QLabel(self.groupBox_6)
        self.label_65.setGeometry(QtCore.QRect(10, 60, 56, 17))
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.label_66 = QtGui.QLabel(self.groupBox_6)
        self.label_66.setGeometry(QtCore.QRect(10, 140, 56, 17))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.label_67 = QtGui.QLabel(self.groupBox_6)
        self.label_67.setGeometry(QtCore.QRect(190, 90, 56, 17))
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.lineEdit_32 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_32.setGeometry(QtCore.QRect(70, 90, 113, 27))
        self.lineEdit_32.setObjectName(_fromUtf8("lineEdit_32"))
        self.label_68 = QtGui.QLabel(self.groupBox_6)
        self.label_68.setGeometry(QtCore.QRect(10, 90, 56, 17))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.line_6 = QtGui.QFrame(self.groupBox_6)
        self.line_6.setGeometry(QtCore.QRect(10, 120, 231, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_69 = QtGui.QLabel(self.groupBox_6)
        self.label_69.setGeometry(QtCore.QRect(190, 160, 56, 17))
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.lineEdit_33 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_33.setGeometry(QtCore.QRect(70, 160, 113, 27))
        self.lineEdit_33.setObjectName(_fromUtf8("lineEdit_33"))
        self.label_70 = QtGui.QLabel(self.groupBox_6)
        self.label_70.setGeometry(QtCore.QRect(10, 160, 56, 17))
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.label_71 = QtGui.QLabel(self.groupBox_6)
        self.label_71.setGeometry(QtCore.QRect(190, 190, 56, 17))
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.lineEdit_34 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_34.setGeometry(QtCore.QRect(70, 190, 113, 27))
        self.lineEdit_34.setObjectName(_fromUtf8("lineEdit_34"))
        self.label_72 = QtGui.QLabel(self.groupBox_6)
        self.label_72.setGeometry(QtCore.QRect(10, 190, 56, 17))
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.line_7 = QtGui.QFrame(self.groupBox_6)
        self.line_7.setGeometry(QtCore.QRect(10, 230, 231, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.label_73 = QtGui.QLabel(self.groupBox_6)
        self.label_73.setGeometry(QtCore.QRect(200, 250, 56, 17))
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.lineEdit_35 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_35.setGeometry(QtCore.QRect(80, 250, 113, 27))
        self.lineEdit_35.setObjectName(_fromUtf8("lineEdit_35"))
        self.label_74 = QtGui.QLabel(self.groupBox_6)
        self.label_74.setGeometry(QtCore.QRect(20, 250, 56, 17))
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout.addWidget(self.groupBox_6, 1, 2, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(70, 20, 113, 27))
        self.lineEdit_9.setObjectName(_fromUtf8("lineEdit_9"))
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(190, 20, 56, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 56, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(70, 50, 113, 27))
        self.lineEdit_10.setObjectName(_fromUtf8("lineEdit_10"))
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setGeometry(QtCore.QRect(190, 50, 56, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 50, 56, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_11 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_11.setGeometry(QtCore.QRect(70, 80, 113, 27))
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(190, 80, 56, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(10, 80, 56, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.line = QtGui.QFrame(self.groupBox_5)
        self.line.setGeometry(QtCore.QRect(10, 100, 231, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(10, 110, 56, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_12 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_12.setGeometry(QtCore.QRect(70, 130, 113, 27))
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setGeometry(QtCore.QRect(190, 130, 56, 17))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setGeometry(QtCore.QRect(10, 130, 56, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_13.setGeometry(QtCore.QRect(70, 160, 113, 27))
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        self.label_26.setGeometry(QtCore.QRect(190, 160, 56, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBox_5)
        self.label_27.setGeometry(QtCore.QRect(10, 160, 56, 17))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.line_2 = QtGui.QFrame(self.groupBox_5)
        self.line_2.setGeometry(QtCore.QRect(0, 180, 241, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.lineEdit_14 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_14.setGeometry(QtCore.QRect(70, 190, 113, 27))
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(190, 190, 56, 17))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(10, 190, 56, 17))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.lineEdit_15 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_15.setGeometry(QtCore.QRect(70, 220, 113, 27))
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.label_30 = QtGui.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(190, 220, 56, 17))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox_5)
        self.label_31.setGeometry(QtCore.QRect(10, 220, 56, 17))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_16.setGeometry(QtCore.QRect(70, 260, 113, 27))
        self.lineEdit_16.setObjectName(_fromUtf8("lineEdit_16"))
        self.label_32 = QtGui.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(190, 260, 56, 17))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(10, 260, 56, 17))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.groupBox_5, 1, 1, 1, 1)
        ScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(ScrollArea)
        QtCore.QMetaObject.connectSlotsByName(ScrollArea)

    def retranslateUi(self, ScrollArea):
        ScrollArea.setWindowTitle(_translate("ScrollArea", "CRLcalc - Offline Test Version ", None))
        self.groupBox.setTitle(_translate("ScrollArea", "X-Ray Source and Detector", None))
        self.Name_Energy.setText(_translate("ScrollArea", "TextLabel", None))
        self.Unit_Energy.setText(_translate("ScrollArea", "TextLabel", None))
        self.unit_WaveLength.setText(_translate("ScrollArea", "TextLabel", None))
        self.Name_WaveLength.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_46.setText(_translate("ScrollArea", "TextLabel", None))
        self.Unit_SSv.setText(_translate("ScrollArea", "TextLabel", None))
        self.Name_SSv.setText(_translate("ScrollArea", "TextLabel", None))
        self.Unit_SSh.setText(_translate("ScrollArea", "TextLabel", None))
        self.Name_SSh.setText(_translate("ScrollArea", "TextLabel", None))
        self.Unit_g.setText(_translate("ScrollArea", "TextLabel", None))
        self.Name_g.setText(_translate("ScrollArea", "TextLabel", None))
        self.Unit_Intensity.setText(_translate("ScrollArea", "TextLabel", None))
        self.Name_Intensity.setText(_translate("ScrollArea", "TextLabel", None))
        self.groupBox_2.setTitle(_translate("ScrollArea", "Copound Refractive Lens Structure", None))
        self.label_34.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_35.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_36.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_37.setText(_translate("ScrollArea", "TextLabel", None))
        self.checkBox.setText(_translate("ScrollArea", "CheckBox", None))
        self.label_38.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_39.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_40.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_41.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_42.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_43.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_44.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_45.setText(_translate("ScrollArea", "TextLabel", None))
        self.groupBox_3.setTitle(_translate("ScrollArea", "Lens Material", None))
        self.label_55.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_56.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_57.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_58.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_59.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_60.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_61.setText(_translate("ScrollArea", "TextLabel", None))
        self.pushButton.setText(_translate("ScrollArea", "PushButton", None))
        self.groupBox_4.setTitle(_translate("ScrollArea", "Lens Properties", None))
        self.label_5.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_6.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_7.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_8.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_9.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_10.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_11.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_12.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_13.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_14.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_15.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_16.setText(_translate("ScrollArea", "TextLabel", None))
        self.groupBox_6.setTitle(_translate("ScrollArea", "Corrected for Diffraction, PSF and Roughness", None))
        self.label_62.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_63.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_64.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_65.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_66.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_67.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_68.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_69.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_70.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_71.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_72.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_73.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_74.setText(_translate("ScrollArea", "TextLabel", None))
        self.groupBox_5.setTitle(_translate("ScrollArea", "Results for Given Geometry", None))
        self.label_17.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_18.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_19.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_20.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_21.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_22.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_23.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_24.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_25.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_26.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_27.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_28.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_29.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_30.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_31.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_32.setText(_translate("ScrollArea", "TextLabel", None))
        self.label_33.setText(_translate("ScrollArea", "TextLabel", None))

